pipeline{
    agent any
 
    tools{
        maven "jenkins-maven"
    }
    environment{
        tomcatWebLocation="\"c:\\apache-tomcat-9.0.55\\webapps\""
        tomcatBinLocation="\"c:\\apache-tomcat-9.0.55\\bin\""
        buildLocation="C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\dxc_maven_build_file_from_scm_deploy_on_tomcat_pipeline_job\\mywebapp\\target\\mywebapp.war"
    }
 
    stages{
 
        stage('Git Checkout'){
            steps{
 
            git 'https://github.com/codewithz/dxc-web-app.git'
            }
        }
 
        stage('Maven Build'){
            steps{
            bat """
                cd mywebapp
                mvn clean package
            """
            }
        }
 
    }
 
    post{
        success{
 
            bat """
                copy %buildLocation%  %tomcatWebLocation%
                %tomcatBinLocation%\\startup.bat
            """
 
        }
    }
}
